import logging.config

import yaml

# allowed URLS
ALLOWED_URLS = ["http://localhost:3000", "https://dashboard.leocelis.com", "https://ada.leocelis.com",
                "https://www.leocelis.com", "https://leocelis.com", "https://api.ada-tool.com",
                "https://www.ada-tool.com"]

# ignore the platforms domains
IGNORE_DOMAINS = ['facebook.com', 'linkedin.com', 'twitter.com', 'twitch.com',
                  'whatsapp.com', 'google.com', 'printfriendly.com', 'bufferapp.com', 'outlook.com',
                  'gmail.com']

# Facebook Ads Optimization
DATA_FOLDER = "./data"

# Content Discovery
SUMMARY_THRESHOLD = 5  # min total shares to make it in the summary table
SHARETHIS_THRESHOLD = 5  # min total actions in Share This
FACEBOOK_SHARES_THRESHOLD = 5  # min shares a link should have
TWITTER_RETWEETS_THRESHOLD = 10  # min retweets a tweet should have
TWITTER_WAIT_REQUESTS = 2  # wait seconds between requests
TWITTER_HISTORY_COUNT = 200  # how many tweets in the past we will consider
# TWITTER_KEYWORDS = ['martech',
#                     '"ad tech"',
#                     'adtech',
#                     '"performance marketing"',
#                     '"growth marketing"',
#                     '"martech stack"',
#                     '"conversion metrics"',
#                     # '"affiliating marketing"',
#                     '"customer acquisition cost"',
#                     '"customer cost of acquisition"',
#                     # '"viral loop"',
#                     '"life cycle marketing"',
#                     '"predict growth"',
#                     '"mobile attribution partners"',
#                     '"lifecycle marketing"',
#                     '"mobile stack"',
#                     '"attribution partners"',
#                     '"mobile growth stack"',
#                     '"modeling growth"',
#                     '"mar tech"',
#                     '"stack market"',
#                     '"chief martech"',
#                     '"marketing technology landscape"',
#                     '"marketing landscape"',
#                     '"martech stack"',
#                     '"marketing stack"',
#                     '"hacking marketing"',
#                     '"chief marketing technology"'
#                     '"ad tech conference"',
#                     '"adtech conference"',
#                     '"ad tech company"',
#                     '"adtech company"',
#                     '"marketing technology conference"',
#                     '"marketing tech conferences"',
#                     '"marketing automation conference"',
#                     '"analytics for marketers"',
#                     # 'socialcode',
#                     '"data analytics for marketers"',
#                     '"data analytics marketing"',
#                     '"customers engagement"',
#                     '"growth hacking"']

TWITTER_KEYWORDS = ['what is marketing',
                    'marketing mix',
                    'free video ads',
                    'marketing strategy',
                    'inbound marketing',
                    'content marketing',
                    'facebook manage ads',
                    'psychographics',
                    'marketing environment',
                    'promotion mix',
                    'time to market',
                    'marketing process',
                    'market development',
                    'top 10 indian direct selling company',
                    'brand equity',
                    'target market',
                    'niche market',
                    'sales promotion',
                    'product mix',
                    'marcom',
                    'psychographic segmentation',
                    'green marketing',
                    'relationship marketing',
                    'types of marketing',
                    '4p marketing',
                    'marketeer',
                    'demographic segmentation',
                    'what is marketing mix',
                    '7ps of marketing',
                    'marketing collateral',
                    'behavioral segmentation',
                    'print ads',
                    'openmarket',
                    'promotion strategy',
                    'marketing positions',
                    'what is target marketing',
                    'what is the definition of marketing',
                    'social marketing',
                    'what is content marketing',
                    'pinterest ads',
                    'neuromarketing',
                    'marketing strategy plan',
                    'business marketing',
                    'market analysis',
                    'twitter ads',
                    'market intelligence',
                    'product marketing',
                    'leads facebook ads',
                    'advertising agency',
                    'search engine marketing',
                    'amazon affiliate marketing',
                    'seo sem',
                    'ad posting',
                    'what is marketing research',
                    'google digital marketing',
                    'market segmentation'
                    'go to market',
                    'earned media',
                    'buzz marketing',
                    'integrated marketing',
                    'mass market',
                    'journal of marketing',
                    'what are influencers',
                    'adtech',
                    'performance marketing',
                    'linkedin ads',
                    'internet marketing',
                    'online advertising',
                    'social media marketing strategy',
                    'ad agency',
                    'cpa marketing',
                    'social media advertising',
                    'marketing consultant',
                    'seo companies',
                    'what is digital marketing',
                    'advertising company',
                    'digital marketing strategy',
                    'omni channel marketing',
                    'guerilla marketing',
                    'go to market strategy',
                    'consumer behavior',
                    'viral marketing',
                    'zoho campaigns',
                    'marketing communication',
                    'b2b b2c',
                    'industry analysis',
                    'global marketing',
                    'social influencer',
                    'marketing channel',
                    'micromarketing',
                    'what b2b',
                    'creatives in advertising',
                    'marketing agency',
                    'video marketing',
                    'digital marketing services',
                    'principles of marketing',
                    'seo marketing',
                    'video ad',
                    'b2b marketing',
                    'facebook video ads',
                    'advertising media',
                    'martech',
                    'integrated marketing communication',
                    'marketing segmentation',
                    'advertising campaign',
                    'sales marketing',
                    'advertising campaign',
                    'direct marketing',
                    'outbound marketing',
                    'customer segmentation',
                    'buyer personas',
                    'google digital unlock',
                    'inbound',
                    'e marketing',
                    'experiential marketing',
                    'what is marketing strategy',
                    'campaign management',
                    'internet marketing services',
                    'ad campaigns',
                    'retail marketing',
                    'marketing assistant jobs',
                    'marketing management careers',
                    'competitor analysis',
                    'service marketing',
                    'marketing campaign',
                    'marketing and advertising',
                    'marketing advertising',
                    'marketing and advertising',
                    'brand management',
                    'brand marketing',
                    ]

# logging
log_yaml_file = 'logger.yaml'

with open(log_yaml_file, 'r') as f:
    log_config_dict = yaml.safe_load(f)
    f.close()

logging.config.dictConfig(log_config_dict)
log = logging.getLogger(__name__)
