# software settings
QUADRANTS = ('EMPLOYEE', 'SELF-EMPLOYEE', 'BUSINESS_OWNER', 'INVESTOR')
# ASSET_CATEGORY = ["STOCK", "REAL_ESTATE", "BUSINESS"]
ASSET_CATEGORY = ["STOCK", "REAL_ESTATE", "BUSINESS"]
CURRENCY = ["USD", "ARS"]
UNIT = 1
USD_ARS_EXCHANGE_RATE = 166

# plan settings
RETIREMENT_AGE = 50
CURRENT_AGE = 39
AVAILABLE_DAY_HOURS = 8
LIQUID_ASSETS_TOTAL = 84000
MONTHLY_INCOME = 9167
MONTHLY_EXPENSES = 1250
AVG_PORTFOLIO_PERFORMANCE = 0.02

# real estate
CONSTRUCTION_ARS_M2_COST = 72500  # Nov 7, 2020

# TODO: add N/1 rule, distribute investments equally, and $1k/mo rule for each asset
